dist: focal
language: shell
services:
  - docker
script:
  - docker pull alpine:latest
  - docker pull kristophjunge/test-saml-idp:latest
  - docker pull postgres:13
  - docker pull golang:1.16-alpine
  - docker pull golang:1.13-alpine3.10
  - echo "Done!!!!"
