dist: focal
language: shell
services:
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull alpine:latest
  - docker pull golang:1.13-alpine3.10
  - docker build .
